version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/application"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/cdk"
    schedule:
      interval: "daily"
